framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true
        storage_factory_id: session.storage.factory.native

    csrf_protection: ~
    form: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
