services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Handler de session PDO pour Heroku
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - '%env(DATABASE_URL)%'
            - { lock_mode: 0 }

    # lier globalement $databaseUrl à la variable d'environnement
    _instanceof:
        App\Service\PdoService:
            bind:
                $databaseUrl: '%env(resolve:DATABASE_URL)%'

    # services spécifiques
    App\Service\PdoService: ~
    App\EventListener\DailyCreditListener:
        tags:
            - { name: 'kernel.event_subscriber' }

    # classes auto-discover
    App\:
        resource: '../src/'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Twig\Extension\AppExtension:
        tags: ['twig.extension']
