parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # lier globalement $databaseUrl à la variable d'environnement
    _instanceof:
        App\Service\PdoService:
            bind:
                $databaseUrl: '%env(resolve:DATABASE_URL)%'

    # services spécifiques
    App\Service\PdoService: ~
    App\EventListener\DailyCreditListener:
        tags:
            - { name: 'kernel.event_subscriber' }

    # classes auto-discover
    App\:
        resource: '../src/'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Twig\AppExtension:
        tags: ['twig.extension']
